In [5]:
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
[ 59.  239.  155.4  76.9]


In [16]:
cal = (A.sum(axis=0))
print(cal)
print(cal.shape)

[ 59.  239.  155.4  76.9]
(4,)


In [9]:
per = 100 * A/cal
print(per)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [21]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print("Value: " + str(c) + " Shape: " + str(c.shape))

Value: [[-1.2931769  -0.95570417 -0.76549108]
 [-2.45114099 -2.60588903 -2.24241853]] Shape: (2, 3)
